version: "3.2"
services:
  php-fpm:
    container_name: '${NAME}-php'
    build:
      context: './php/'
    volumes:
      - ../${NAME}:/var/www/app/
      - ./logs:/var/log
      - ./php/.composer/:/home/kuba/.composer
#  cron:
#    build:
#      args:
#        php_version: ${PHP_VERSION}
#      context: ./cron
#    restart: always
#    volumes:
#      - ./src/magento:/var/www/magento:cached
  nginx:
    container_name: '${NAME}-nginx'
    build: './nginx/'
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../${NAME}:/var/www/app/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./logs:/var/log
  mariadb:
    container_name: '${NAME}-mariadb'
    build:
      context: ./mariadb
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ../${NAME}:/var/www/app/
      - ./mariadb/conf.d:/etc/mysql/conf.d
      - ./mariadb/local/data:/var/lib/mysql/data
      - ./logs:/var/log
    ports:
      - "3306:3306"
  phpmyadmin:
    container_name: '${NAME}-pma'
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mariadb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER_container_name=root
  ngrok:
    container_name: '${NAME}-ngrok'
    image: shkoliar/ngrok:latest
    ports:
      - 4551:4551
    links:
      - nginx
    environment:
      - DOMAIN=nginx
      - PORT=80
    volumes:
      - ../${NAME}:/var/www/app/
  es:
    container_name: '${NAME}-es'
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.1
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
     - "9200:9200"
     - "9300:9300"
    volumes:
     - ./elasticsearch/data:/usr/share/elasticsearch/data
  redis:
    container_name: '${NAME}-redis'
    build:
      context: ./redis
networks:
  default:
    driver: bridge
